exports.run = function (req$959) {
    var output$960 = [];
    output$960.push('<', 'div', ' id="info"', ' class="panel"', '>');
    output$960.push('<', 'div', ' class="panel_title"', '>');
    output$960.push('\u4E2A\u4EBA\u8D44\u6599');
    output$960.push('</', 'div', '>');
    output$960.push('<', 'div', ' class="panel_content"', '>');
    output$960.push('<', 'div', ' class="info_img"', '>');
    output$960.push('<', 'img', ' src="', '/icons/' + req$959.user.icon, '"', ' alt="', req$959.user.nickname, '"', ' title="', req$959.user.nickname, '"', '/>');
    output$960.push('</', 'div', '>');
    output$960.push('<', 'div', ' class="info_name"', '>');
    output$960.push(req$959.user.nickname);
    output$960.push('</', 'div', '>');
    output$960.push('<', 'div', ' class="hr"', '>');
    output$960.push('</', 'div', '>');
    output$960.push('<', 'div', ' class="info_intro"', '>');
    output$960.push(req$959.user.description);
    output$960.push('</', 'div', '>');
    output$960.push('</', 'div', '>');
    output$960.push('</', 'div', '>');
    return output$960.join('');
};