var lib$907 = require('./lib');
exports.run = function (req$909, data$910) {
    var output$911 = [];
    var path$912 = '/blog/' + req$909.user.id, title$913 = req$909.user.nickname + '\u7684\u535A\u5BA2';
    output$911.push('<!DOCTYPE html><html>');
    output$911.push('<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />');
    output$911.push(lib$907.title(title$913));
    output$911.push(lib$907.style('/css/ui.css'));
    output$911.push(lib$907.style('/css/main.css'));
    output$911.push('</head>');
    output$911.push('<body>');
    output$911.push('<', 'div', ' id="toolbar"', '>');
    output$911.push('<', 'span', '>');
    if (req$909.session.user) {
        output$911.push('<', 'a', ' href="', '/blog/' + req$909.session.user.id, '"', '>');
        output$911.push(req$909.session.user.nickname + '\u7684\u535A\u5BA2');
        output$911.push('</', 'a', '>');
        output$911.push(' ');
        output$911.push('<', 'a', ' href="', '/logout?goto=' + path$912, '"', '>');
        output$911.push('\u9000\u51FA');
        output$911.push('</', 'a', '>');
    } else {
        output$911.push('<', 'a', ' href="', '/login', '"', '>');
        output$911.push('\u767B\u5F55');
        output$911.push('</', 'a', '>');
    }
    output$911.push('</', 'span', '>');
    output$911.push('</', 'div', '>');
    output$911.push('<', 'div', ' id="header"', '>');
    output$911.push('<', 'div', ' id="title"', '>');
    output$911.push('<', 'h1', ' id="name"', '>');
    output$911.push('<', 'a', ' href="', '#', '"', '>');
    output$911.push(title$913);
    output$911.push('</', 'a', '>');
    output$911.push('</', 'h1', '>');
    output$911.push('<', 'div', ' id="link"', '>');
    output$911.push('<', 'a', ' href="', '#', '"', '>');
    output$911.push('http://localhost' + path$912);
    output$911.push('</', 'a', '>');
    output$911.push('</', 'div', '>');
    output$911.push('</', 'div', '>');
    output$911.push('<', 'div', ' id="nav"', '>');
    output$911.push('<', 'span', '>');
    output$911.push('<', 'a', ' href="', path$912, '"', data$910.nav === 0 ? 'class="current"' : '', '>');
    output$911.push('\u4E3B\u9875');
    output$911.push('</', 'a', '>');
    output$911.push('</', 'span', '>');
    output$911.push('|');
    output$911.push('<', 'span', '>');
    output$911.push('<', 'a', ' href="', path$912 + '/blog_list', '"', data$910.nav === 1 ? 'class="current"' : '', '>');
    output$911.push('\u535A\u5BA2\u76EE\u5F55');
    output$911.push('</', 'a', '>');
    output$911.push('</', 'span', '>');
    output$911.push('</', 'div', '>');
    output$911.push('</', 'div', '>');
    output$911.push('<', 'div', ' id="body"', '>');
    if (data$910.nav === 1) {
        output$911.push('<', 'a', ' id="post_blog"', ' class="align_right"', ' href="', path$912 + '/edit', '"', '>');
        output$911.push('\u53D1\u535A\u6587');
        output$911.push('</', 'a', '>');
        output$911.push('<', 'div', ' class="clear"', '>');
        output$911.push('</', 'div', '>');
    }
    output$911.push('<', 'div', ' id="body_left"', '>');
    output$911.push(data$910.bodyLeft);
    output$911.push('</', 'div', '>');
    output$911.push('<', 'div', ' id="body_right"', '>');
    output$911.push(data$910.bodyRight);
    output$911.push('</', 'div', '>');
    output$911.push('</', 'div', '>');
    output$911.push('<', 'div', ' id="footer"', '>');
    output$911.push('<', 'p', '>');
    output$911.push('Copyright &copy; 2015 ' + req$909.user.nickname);
    output$911.push('</', 'p', '>');
    output$911.push('<', 'p', '>');
    output$911.push(req$909.user.nickname + '\u7248\u6743\u6240\u6709');
    output$911.push('</', 'p', '>');
    output$911.push('</', 'div', '>');
    output$911.push('</body>');
    output$911.push('</html>');
    return output$911.join('');
};